export const ADD_JOB_OFFER = 'ADD_JOB_OFFER';
export const DELETE_JOB_OFFER = 'DELETE_JOB_OFFER';
export const EDIT_JOB_OFFER = 'EDIT_JOB_OFFER';

// VISIBILITY_FILTER
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';